### ISSUE TITLE
py2exe crashes on use

### ISSUE THREAD

**Issue by not-a-seagull** [albertosottile/py2exe#15]
When I attempt to use py2exe on my program, I get the following error:

`Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(console="main.py")
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Users\Andy\AppData\Local\Programs\Python\Python37\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)`

The command I am using is `python setup.py p2exe`. Here is the file:

`
from setuptools import setup
import py2exe

setup(console="main.py")
`

**Comment by albertosottile** [comment]
Hi, thanks for reporting this.

The actual exception is missing from your log, did you forget to paste the last lines? 

Also, would it be possible for you to post here the code of your program (or at least a minimal subset of it that still causes this error)?

**Comment by not-a-seagull** [comment]
Apologies, the exception is: `IndexError: tuple index out of range`

My program is a large, multi-file program including PyQt, pandas, numpy, and matplotlib. I think it is outside my ability to find out which part of it is causing this error.

**Comment by albertosottile** [comment]
I understand, but this will make this issue way more difficult to debug. Which version of py2exe are you running? Could you at least provide me a list of all the modules imported by your project?

**Comment by not-a-seagull** [comment]
I am using py2exe v0.9.2.2. The modules used by my project are lxml, matplotlib, mpl-data, numpy, pandas, PIL, PyQt5, pytz, tcl, tk, win32com, and their dependencies. The program's purpose is the generate an [IDML file](http://wwwimages.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/idml/idml-specification.pdf) by reading another IDML file and replacing text.

**Comment by albertosottile** [comment]
This repository refers only to my fork, so I encourage you to install version 0.9.3.1, downloadable from the release page. The version you are using does not support Python 3.7.
