### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Monism1** [albertosottile/py2exe#17]
Hello, I received the following message after running python ..\setup.py py2exe 

> Traceback (most recent call last):
  File "hello.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\rmhan\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import random
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\rmhan\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\random\__init__.py", line 180, in <module>
    from . import mtrand
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
SystemError: <method 'load_module' of 'zipimport.zipimporter' objects> returned NULL without setting an error
>

**Comment by Monism1** [comment]
mistakenly submitted
