### ISSUE TITLE
Error when using numpy or numba with py2exe

### ISSUE THREAD

**Issue by Keithcat1** [albertosottile/py2exe#28]
Hi and thanks for py2exe. It's a really cool piece of code. It can't handle numba or numpy though.
The error for numpy is:
Traceback (most recent call last):
  File "zipextimporter.pyc", line 87, in load_module
zipimport.ZipImportError: can't find module 'numpy.random.mtrand'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "numpy\__init__.pyc", line 150, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "numpy\random\__init__.pyc", line 181, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "numpy\random\_pickle.pyc", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 112, in load_module
SystemError: initialization of numpy.random.mtrand did not return an extension module

If I try to use numba:
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "numba\__init__.pyc", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "numba\config.pyc", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "llvmlite\binding\__init__.pyc", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "llvmlite\binding\dylib.pyc", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "llvmlite\binding\ffi.pyc", line 154, in <module>
OSError: Could not load shared object file: llvmlite.dll
It looks like py2exe didn't include llvmlite.dll, which is required by llvmlite.
Also, Cryptodome or at least Cryptodome.Cipher.AES can't be used:
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "Cryptodome\Cipher\__init__.pyc", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "Cryptodome\Cipher\_mode_ecb.pyc", line 47, in <module>
  File "Cryptodome\Util\_raw_api.pyc", line 300, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win32.pyd': cannot load library 'C:\py\dist\test.exe\Cryptodome\Util\..\Cipher\_raw_ecb.cp37-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\py\\dist\\test.exe\\Cryptodome\\Util\\..\\Cipher\\_raw_ecb.cp37-win32.pyd', Trying '_raw_ecb.pyd': cannot load library 'C:\py\dist\test.exe\Cryptodome\Util\..\Cipher\_raw_ecb.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\py\\dist\\test.exe\\Cryptodome\\Util\\..\\Cipher\\_raw_ecb.pyd'

Thanks!

**Comment by snodo** [comment]
This "solution" helped me:
[https://programmer.ink/think/py2exe-packaging-oss2-and-pycryptodome-failure-problem-investigation.html](url)

I changed util_lib and root_lib variables only if hasattr(sys, "frozen"), so pycryptodome works when running with interpreter aswell as running out of the *.exe file.

I also added a bit code to my exeBuilder.py which copies all the needed *.pyd files to the correct location.

Not really nice, but it works flawlessly for my project.

**Comment by albertosottile** [comment]
Numpy compatibility should be fixed in 0.10.0.2 (currently in pre-release). Numba is a very complicated module to get fully compatible with so, at the moment, I think I will prioritize other modules. Hence, I am closing this for now.
