### ISSUE TITLE
Failure to import numpy after py2exe

### ISSUE THREAD

**Issue by urishab** [albertosottile/py2exe#3]
Hi I have another issue where the compiled application fails to import numpy even though the py2exe process seems successful

my test3.py:
```
import numpy
print('hello')
```

and my py2exe_test3.py:
```
from distutils.core import setup
import py2exe #@UnusedImport
setup( console=[{ "script": "test3.py",},],
       options={"py2exe": {
            "packages": ['numpy'],
       }})

```
and I run:
`python py2exe_test3.py py2exe
`
I get the following message when trying to run the resulting test3.exe:
```
Traceback (most recent call last):
  File "C:\Projects\pyenv\lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "C:\Projects\pyenv\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Projects\pyenv\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: The specified module could not be found.) 'C:\\Projects\\code\\dist\\numpy.core._multiarray_umath.pyd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test3.py", line 1, in <module>
  File "C:\Projects\pyenv\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Projects\pyenv\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Projects\code\dist\test3.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: (DLL load failed: The specified module could not be found.) 'C:\\Projects\\code\\dist\\numpy.core._multiarray_umath.pyd'

```
My pip freeze:
```
numpy==1.16.2
opencv-python==4.0.0.21
Pillow==6.0.0
py2exe==0.9.3.0
pyserial==3.4
pywin32==224
reportlab==3.5.18
six==1.12.0
wxPython==4.0.4
xlwt==1.3.0
```

And Python version:
`Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32`

**Comment by albertosottile** [comment]
This can probably be fixed by adjusting the numpy code in hooks.py. Once again, I'll check it once I have access to my computer again.

**Comment by albertosottile** [comment]
I found the missing DLL (libopenblas) and adjusted the numpy hook code. A fix commit is coming soon. Thanks for reporting this.
